use wine_pairing;


INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Meat", "Red Meat", "Venison");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red","Meat", "Cured Meat", "Salami");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White","Meat", "Cured Meat", "Salami");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red","Meat", "Cured Meat", "Proscuitto");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White","Meat", "Cured Meat", "Proscuitto");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Meat", "Cured Meat", "Bresaola");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Meat", "Cured Meat", "Bresaola");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Meat", "Cured Meat", "Bacon");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Meat", "Cured Meat", "Bacon");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red","Meat", "Pork", "Roast");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Meat", "Pork", "Tenderloin");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Meat", "Pork", "Pork Chop");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Meat", "Poultry", "Chicken");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Meat", "Poultry", "Chicken");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Meat", "Poultry", "Duck");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Meat", "Poultry", "Duck");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Meat", "Poultry", "Turkey");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Meat", "Poultry", "Turkey");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (7, "Sparkling", "Meat", "Mollusk", "Oyster");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (7, "Sparkling", "Meat", "Mollusk", "Mussel");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (7, "Sparkling", "Meat", "Mollusk", "Clam");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Meat", "Fish (Incl. Raw)", "Tuna");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Meat", "Fish (Incl. Raw)", "Cod");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Meat", "Fish (Incl. Raw)", "Trout");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Meat", "Fish (Incl. Raw)", "Bass");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Meat", "Lobster & Shellfish", "Prawn");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Meat", "Lobster & Shellfish", "Crab");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Dairy", "Soft Cheese & Cream", "Brie");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Dairy", "Soft Cheese & Cream", "Brie");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Dairy", "Soft Cheese & Cream", "Mascarpone");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Dairy", "Soft Cheese & Cream", "Mascarpone");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Dairy", "Soft Cheese & Cream", "Creme Fraiche");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Dairy", "Soft Cheese & Cream", "Creme Fraiche");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Dairy", "Pungent Cheese", "Bleu");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Dairy", "Pungent Cheese", "Bleu");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Dairy", "Pungent Cheese", "Gorgonzola");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Dairy", "Pungent Cheese", "Gorgonzola");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Dairy", "Pungent Cheese", "Stilton");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Dairy", "Pungent Cheese", "Stilton");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Dairy", "Pungent Cheese", "Roquefort");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Dairy", "Pungent Cheese", "Roquefort");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Dairy", "Hard Cheese", "Cheddar");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Dairy", "Hard Cheese", "Pecorino");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Dairy", "Hard Cheese", "Manchego");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Dairy", "Hard Cheese", "Parmesan");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "Alliums", "Onion");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "Alliums", "Shallot");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "Alliums", "Garlic");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "Alliums", "Scallion");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Vegetable", "Green Vegetables", "Green Bean");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Vegetable", "Green Vegetables", "Kale");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Vegetable", "Green Vegetables", "Lettuce");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (4, "Rose","Vegetable", "Root Vegetables & Squash", "Turnip");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (4, "Rose","Vegetable", "Root Vegetables & Squash", "Butternut Squash");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (4, "Rose", "Vegetable", "Root Vegetables & Squash", "Pumpkin");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (4, "Rose", "Vegetable", "Root Vegetables & Squash", "Delicata");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (4, "Rose", "Vegetable", "Root Vegetables & Squash", "Carrot");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "NightShades", "Tomato");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "NightShades", "Eggplant");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "NightShades", "Bell Pepper");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red","Vegetable", "Funghi", "Crimini");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red","Vegetable", "Funghi", "Crimini");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White","Vegetable", "Funghi", "Crimini");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "Funghi", "Maitake");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Vegetable", "Funghi", "Maitake");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Vegetable", "Funghi", "Maitake");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Vegetable", "Funghi", "Chanterelle");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (3, "Light Red", "Vegetable", "Funghi", "Chanterelle");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (5, "Rich White", "Vegetable", "Funghi", "Chanterelle");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Vegetable", "Nuts & Seeds", "Peanut");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Vegetable", "Nuts & Seeds", "Almond");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Vegetable", "Nuts & Seeds", "Pecan");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Vegetable", "Nuts & Seeds", "Sesame");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Vegetable", "Beans & Peas", "Lentil");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Vegetable", "Beans & Peas", "Navy");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Vegetable", "Beans & Peas", "Pinto");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Vegetable", "Beans & Peas", "Chickpea");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Herb & Spice", "Black Pepper", "Black Pepper");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Red Pepper", "Herb & Spice", "Red Pepper", "Ancho");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Red Pepper", "Herb & Spice", "Red Pepper", "Aleppo");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Red Pepper", "Herb & Spice", "Red Pepper", "Chipotle");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Red Pepper", "Herb & Spice", "Red Pepper", "Chili");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Hot & Spicy", "Hot Sauce");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Hot & Spicy", "Habanero");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Hot & Spicy", "Sichuan");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Herb & Spice", "Herbs", "Thyme");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Herb & Spice", "Herbs", "Oregano");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Herb & Spice", "Herbs", "Basil");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (6, "Light White", "Herb & Spice", "Herbs", "Tarragon");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Herb & Spice", "Baking Spices", "Cinnamon");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Herb & Spice", "Baking Spices", "Clove");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Herb & Spice", "Baking Spices", "Allspice");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Herb & Spice", "Baking Spices", "Mace");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Herb & Spice", "Exotic & Aromatic Spices", "Anise");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Exotic & Aromatic Spices", "Anise");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Herb & Spice", "Exotic & Aromatic Spices", "Tumeric");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Exotic & Aromatic Spices", "Tumeric");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Herb & Spice", "Exotic & Aromatic Spices", "Saffron");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Exotic & Aromatic Spices", "Saffron");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Herb & Spice", "Exotic & Aromatic Spices", "Fennel");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Exotic & Aromatic Spices", "Fennel");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (2, "Medium Red", "Herb & Spice", "Exotic & Aromatic Spices", "Ginger");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Herb & Spice", "Exotic & Aromatic Spices", "Ginger");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Starch", "White Starches", "Flour");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Starch", "White Starches", "White Rice");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Starch", "White Starches", "Pasta");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Starch", "White Starches", "Bread");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Starch", "White Starches", "Tortillas");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Starch", "Whole Wheat Grains", "Quinoa");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Starch", "Whole Wheat Grains", "Farro");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Starch", "Whole Wheat Grains", "Brown Rice");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Starch", "Sweet Starchy Vegetables", "Sweet Potato");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Starch", "Sweet Starchy Vegetables", "Yucca");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Starch", "Sweet Starchy Vegetables", "Taro");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (1, "Bold Red", "Starch", "Potato", "Potato");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Sweet", "Fruit & Berries", "Strawberry");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Sweet", "Fruit & Berries", "Orange");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Sweet", "Fruit & Berries", "Apple");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Sweet", "Fruit & Berries", "Peach");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Sweet", "Vanilla & Caramel", "Creme Brulee");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (8, "Sweet White", "Sweet", "Fruit & Berries", "Ice Cream");
INSERT INTO wine_foods (wine_id, wine_class, food_category, food_class, food_name) VALUES (9, "Dessert", "Sweet", "Chocolate & Coffee", "Chocolate & Coffee");


use wine_pairing;

INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (1, "Bold Red", "Malbec", "Mt. Brave, Malbec, Mount Veeder, 2014");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (1, "Bold Red", "Syrah/Shiraz", "Plumpjack Winery, Syrah, Napa Valley, 2013");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (1, "Bold Red", "Cabernet Sauvignon", "Hundred Acre, Deep Time Cabernet Sauvignon, Napa Valley, 2007");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (2, "Medium Red", "Merlot", "Duckhorn Vineyards Estate, Grown Merlot, Napa Valley, 2006");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (2, "Medium Red", "Zinfandel", "Chateau Montelena Estate, Zinfandel, Napa Valley, 2006");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (2, "Medium Red", "Tempranillo", "Gramercy Cellars, Inigo Montoya Tempranillo, Walla Walla Valley, 2009");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (3, "Light Red", "Gamay", "Clos Roche Blanche, Cuvee Gamay, Touraine, 2007");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (3, "Light Red", "Pinot Noir", "El Molino, Rutherford Pinot Noir, Napa Valley, 2013");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (3, "Light Red", "Grenache", "Gramercy Cellars, The Third Man Grenache - Syrah - Mourvedre, Columbia Valley, 2010");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (4, "Rose", "White Zinfandel", "None");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (4, "Rose", "Pinot Noir Rose", "None");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (4, "Rose", "Syrah Rose", "None");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (5, "Rich White", "Chardonnay", "Kongsgaard, The Judge Chardonnay, White, Napa Valley, 2014");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (5, "Rich White", "Semillon", "Mendel, Semillon, Blanco, La Consulta, 2016");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (5, "Rich White", "Viognier", "Joseph Phelps Vineyards, Viognier, White, Napa Valley, 2000");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (6, "Light White", "Sauvignon Blanc", "Araujo Estate, Eisele Vineyard Sauvignon Blanc, White, Napa Valley, 2010");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (6, "Light White", "Pinot Blanc", "Robert Foley Vineyards, Pinot Blanc, White, Napa Valley, 2006");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (6, "Light White", "Pinot Gris / Pinot Grigio", "Etude, Pinot Gris, White, Carneros, 2009");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (7, "Sparkling", "Champagne", "Dom Perignon, Brut, Blanc, Champagne, 2009");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (7, "Sparkling", "Sparkling Wine", "None");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (7, "Sparkling", "Sparkling Rose", "None");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (8, "Sweet Wine", "Moscato", "Planeta, Moscato Bianco, White, Noto, 2013");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (8, "Sweet Wine", "Riesling", "Smith Madrone, Riesling, White, Spring Mountain District, 2013");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (8, "Sweet Wine", "Chenin Blanc", "Pine Ridge Vineyards, Chenin Blanc - Viognier, White, Napa Valley, 2011");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (9, "Dessert Wine", "Port", "None");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (9, "Dessert Wine", "Sherry", "None");
INSERT INTO wine_bottle (wine_id, wine_class, wine_name, wine_bottle) VALUES (9, "Dessert Wine", "Madeira", "None");